version: '3'

vars:
  GO_VERSION: '1.24'
  GOLANGCI_LINT_VERSION: 'v2.1.5'
  GCI_VERSION: 'v0.13.6'
  GOFUMPT_VERSION: 'v0.8.0'

  MODULES: assembly inventory order payment platform iam notification

  BIN_DIR: '{{.ROOT_DIR}}/bin'

tasks:

  install-formatters:
    desc: "Устанавливает gofumpt и gci (Windows + Linux)"
    cmds:
      - cmd: |
          mkdir -p {{.BIN_DIR}}
          if [ ! -f "{{.BIN_DIR}}/gofumpt" ]; then
            echo "📦 Installing gofumpt {{.GOFUMPT_VERSION}}"
            GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
          fi
          if [ ! -f "{{.BIN_DIR}}/gci" ]; then
            echo "📦 Installing gci {{.GCI_VERSION}}"
            GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
          fi
        platforms: [linux, darwin]

      - cmd: |
          if (!(Test-Path "{{.BIN_DIR}}")) {
            New-Item -ItemType Directory -Force "{{.BIN_DIR}}" | Out-Null
          }
          if (!(Test-Path "{{.BIN_DIR}}\gofumpt.exe")) {
            Write-Host "📦 Installing gofumpt {{.GOFUMPT_VERSION}}"
            $env:GOBIN="{{.BIN_DIR}}"
            go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
          }
          if (!(Test-Path "{{.BIN_DIR}}\gci.exe")) {
            Write-Host "📦 Installing gci {{.GCI_VERSION}}"
            $env:GOBIN="{{.BIN_DIR}}"
            go install github.com/daixiang0/gci@{{.GCI_VERSION}}
          }
        platforms: [windows]

  install-golangci-lint:
    desc: "Устанавливает golangci-lint"
    cmds:
      - cmd: |
          mkdir -p {{.BIN_DIR}}
          if [ ! -f "{{.BIN_DIR}}/golangci-lint" ]; then
            echo "📦 Installing golangci-lint {{.GOLANGCI_LINT_VERSION}}"
            GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
          fi
        platforms: [linux, darwin]

      - cmd: |
          if (!(Test-Path "{{.BIN_DIR}}")) {
            New-Item -ItemType Directory -Force "{{.BIN_DIR}}" | Out-Null
          }
          if (!(Test-Path "{{.BIN_DIR}}\golangci-lint.exe")) {
            Write-Host "📦 Installing golangci-lint {{.GOLANGCI_LINT_VERSION}}"
            $env:GOBIN="{{.BIN_DIR}}"
            go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
          }
        platforms: [windows]

  lint:
    desc: "Запускает golangci-lint для всех модулей"
    deps: [ install-golangci-lint ]
    cmds:
      - cmd: |
          for module in {{.MODULES}}; do
            if [ -d "$module" ]; then
              echo "🔍 Linting $module"
              {{.BIN_DIR}}/golangci-lint run "$module/..." --config=.golangci.yml
            fi
          done
        platforms: [linux, darwin]

      - cmd: |
          $modules = "{{.MODULES}}".Split(" ")
          foreach ($module in $modules) {
            if (Test-Path $module) {
              Write-Host "🔍 Linting $module"
              & "{{.BIN_DIR}}\golangci-lint.exe" run "$module/..." --config=.golangci.yml
            }
          }
        platforms: [windows]
